version: "3.8"

services:
  api:
    image: bdomingo/profiling-api:latest
    container_name: profiling-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: profiling-db
    restart: always
