"""Add AttendanceLog table

Revision ID: 07615e7d19c7
Revises: 539ce6153644
Create Date: 2023-04-14 06:19:52.849003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07615e7d19c7'
down_revision = '539ce6153644'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendancelog',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendancelog')
    # ### end Alembic commands ###
