"""Added Profile.suffix field

Revision ID: 539ce6153644
Revises: 69568d266116
Create Date: 2023-03-19 12:48:18.058956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539ce6153644'
down_revision = '69568d266116'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('suffix', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'suffix')
    # ### end Alembic commands ###
